---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Blog
- type: document
  path: exampleSite/content/blog/_index.md
  label: Blog
- type: directory
  path: exampleSite/content/blog
  label: Blog Posts
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - create-new-post
- type: heading
  label: Author
- type: directory
  path: exampleSite/content/author
  label: Author
  create: all
  match: "*"
  templates:
  - create-new-author
- type: heading
  label: About
- type: document
  path: exampleSite/content/about.md
  label: About
- type: heading
  label: Contact
- type: document
  path: exampleSite/content/contact.md
  label: Contact
- type: heading
  label: Privacy
- type: document
  path: exampleSite/content/privacy.md
  label: Privacy
- type: heading
  label: Terms & Conditions
- type: document
  path: exampleSite/content/terms-conditions.md
  label: Terms
- type: heading
  label: All Pages
- type: directory
  path: exampleSite/content
  label: All Pages
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - new-page
- type: heading
  label: Configuration
- type: document
  path: exampleSite/config.toml
  label: Configuration
upload_dir: exampleSite/assets/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.90.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.90.1
